WITH ECOLI_RANK AS (
    SELECT 
        ID,
        SIZE_OF_COLONY,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_RANK
    FROM ECOLI_DATA
)

SELECT 
    E.ID,
    CASE 
        WHEN E.COLONY_RANK = 1 THEN 'CRITICAL'
        WHEN E.COLONY_RANK = 2 THEN 'HIGH'
        WHEN E.COLONY_RANK = 3 THEN 'MEDIUM'
        WHEN E.COLONY_RANK = 4 THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_RANK E
ORDER BY E.ID;
