WITH ECOLI_RANK AS (
    SELECT 
        ID,
        SIZE_OF_COLONY,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_RANK
    FROM ECOLI_DATA
)

SELECT 
    E.ID,
    CASE 
        WHEN E.COLONY_RANK = 1 THEN 'CRITICAL'
        WHEN E.COLONY_RANK = 2 THEN 'HIGH'
        WHEN E.COLONY_RANK = 3 THEN 'MEDIUM'
        WHEN E.COLONY_RANK = 4 THEN 'LOW'
    END AS COLONY_NAME
FROM ECOLI_RANK E
ORDER BY E.ID;

**  WITH 절 기본 개념
    
    WITH [crt_name] AS {
        SELECT
        FROM
    }
    SELECT 
    FROM
 


** 다른 방법

WITH SORTED_ECOLI AS (
    SELECT 
        ID,
        SIZE_OF_COLONY,
        ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RN,
        (SELECT COUNT(*) FROM ECOLI_DATA) AS TOTAL_COUNT
    FROM ECOLI_DATA
)

SELECT 
    ID,
    CASE 
        WHEN RN <= TOTAL_COUNT * 0.25 THEN 'CRITICAL'
        WHEN RN <= TOTAL_COUNT * 0.50 THEN 'HIGH'
        WHEN RN <= TOTAL_COUNT * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM SORTED_ECOLI
ORDER BY ID;
