SELECT M.MEMBER_NAME
        ,R.REVIEW_TEXT
        ,DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;

** LIMIT 1로 리뷰를 가장 많이 작성한 회원 ID를 조건으로 만들고 그 값에 따른 회원 이름, 리뷰 텍스트, 리뷰 작성일을 확인

** 최적화된 다른 코드

WITH MAX_REVIEWER AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)

SELECT M.MEMBER_NAME,
       R.REVIEW_TEXT,
       DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
ON R.MEMBER_ID = M.MEMBER_ID
JOIN MAX_REVIEWER MR
ON R.MEMBER_ID = MR.MEMBER_ID
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;

